### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by Maxdesigna7x** [CrimsonDawn45/Fabric-Shield-Lib#38]
seams to when put in mods servers folder not load fine, LAN server.

**Comment by CringeStar** [comment]
1. What version of the library are you using?
2. Does the version match what the mod requires?
3. And if yes, please describe further.

**Comment by CrimsonDawn45** [comment]
Also could you please post a Pastebin of the full error log.

**Comment by CrimsonDawn45** [comment]
I ran the file on a server myself and got an error log https://pastebin.com/yX6tAyMW

**Comment by CringeStar** [comment]
Line 76 is 

` public static final EntityModelLayer fabric_shield_model_layer = new EntityModelLayer(new Identifier(MOD_ID, "fabric_shield"),"main");`

Probably another dev environment check would be good to have. We could split the making and the assigning of the variable so that it is assigned inside of the onInitialize dev check

**Comment by CrimsonDawn45** [comment]
it's because the RendererMixin should be under "client" in fabricshieldlib.mixins.json it's trying to inject into rendering code that doesn't exist on the server.

**Comment by CrimsonDawn45** [comment]
Fixed in 1.4.2
