### ISSUE TITLE
Game crash fabricshieldlib provided by basicshields

### ISSUE THREAD

**Issue by JustFoxx** [CrimsonDawn45/Fabric-Shield-Lib#81]
[latest.log](https://github.com/CrimsonDawn45/Fabric-Shield-Lib/files/8190491/latest.log)
1.18.1 fabric latest

**Comment by CrimsonDawn45** [comment]
This is because versions 1.5.1 & 1.5.2 aren't compatible with 1.18 even though they are listed as such on Curse Forge. Meaning Curse will automatically download the updated files that don't work on 1.18.1. This has been fixed so Curse will no longer say those versions are compatible with 1.18.1. Switching to version 1.5.0 should fix the issue.
